# Generated by Django 3.1.4 on 2021-01-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Info',
        ),
    ]
