# Generated by Django 3.1.4 on 2021-01-03 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20210103_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
